[General]
; Hotkey: 37 = K. Unbound in MCM = -1 (INI scrive 0 per il plugin).
iKeycode = 37
iEnableWidget = 1
iBestiaryWidget_X = 1360
iBestiaryWidget_Y = 250
fBestiaryWidgetScale = 1.0
iEnableSystemMenuOption = 1
sTutorialMessage = Press [{}] to access your bestiary.
